/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/

USE DataWarehouseAnalytics
GO

/*
===============================================================================
01 - Total customers by countries
===============================================================================
*/

SELECT
    country,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

/*
===============================================================================
02 - Total customers by gender
===============================================================================
*/

SELECT
    gender,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;

/*
===============================================================================
03 - Total products by category
===============================================================================
*/

SELECT
    category,
    COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;

/*
===============================================================================
04 - Average costs in each category
===============================================================================
*/

SELECT
    category,
    CAST(AVG(cost) AS DECIMAL(18,2)) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC;

/*
===============================================================================
05 - Total revenue generated for each category
===============================================================================
*/

WITH rev AS (SELECT
    p.category AS category,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
    ON p.product_key = f.product_key
GROUP BY p.category)

SELECT *, 
    CONCAT(CAST(total_revenue * 100 / Sum(total_revenue) over() AS DECIMAL(4,2)), ' %') As revenue_percent
FROM rev
ORDER BY total_revenue DESC;

/*
===============================================================================
06 - Total revenue generated by each customer
===============================================================================
*/

WITH rev AS (SELECT
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name)

SELECT *, 
    CONCAT(CAST(total_revenue * 100 / Sum(total_revenue) over() AS DECIMAL(4,2)), ' %') As revenue_percent
FROM rev
ORDER BY total_revenue DESC;

/*
===============================================================================
07 - Distribution of sold items across countries
===============================================================================
*/

WITH dis AS (SELECT
    c.country,
    SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY c.country)
SELECT *, 
    CONCAT(CAST(total_sold_items * 100 / Sum(total_sold_items) over() AS DECIMAL(4,2)), ' %') As sold_item_percent
FROM dis
ORDER BY total_sold_items DESC;
